- name: Set fact for GLB Host for {{ host.name | default(host.hostname + '.' + host.domain) }}
  ansible.builtin.set_fact:
    fad_api_endpoint_glb_hosts: >
      https://{{ ansible_host }}/api/global_load_balance_host?vdom={{ fad_vdom }}&mkey={{ host.name | default(host.hostname + '.' + host.domain) }}
    fad_glb_host_name: "{{ host.name | default(host.hostname + '.' + host.domain) }}"
    fad_glb_host_request_body: |
      {
      "mkey": "{{ host.name | default(host.hostname + '.' + host.domain) }}",
      "default-feedback-ip": "{{ host.default_ipv4 | default('0.0.0.0') | string }}",
      "default-feedback-ip6": "{{ host.default_ipv6 | default('::') | string }}",
      "host-name": "{{ host.hostname }}",
      "domain-name": "{{ host.domain }}.",
      "fortiview": "{{ host.fortiview | default('enable') }}",
      "load-balance-method": "{{ host.load_balance_method | default('weight') }}",
      "persistence": "{{ host.persistence | default('enable') }}",
      "respond-single-record": "{{ host.respond_single_record | default('enable') }}"
      }

- name: Print out the GLB Hosts REST API endpoint for {{ fad_glb_host_name }}
  ansible.builtin.debug:
    msg: "Current endpoint: {{ fad_api_endpoint_glb_hosts }}"
  tags:
    - debug

- name: Get the existing value of GLB Host data or {{ fad_glb_host_name }}
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_glb_hosts }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_glb_host_existing_data

- name: Print out the existing value of GLB Host data ({{ fad_glb_host_name }}).
  ansible.builtin.debug:
    var: fad_glb_host_existing_data.json.payload
  tags:
    - debug

- name: Print out the request body json for {{ fad_glb_host_name }}
  ansible.builtin.debug:
    var: request_body
  tags:
    - debug

- name: Create new GLB Host entry if entry don't exists yet for {{ fad_glb_host_name }}
  ansible.builtin.uri:
    method: POST
    url: "{{ fad_api_endpoint_glb_hosts }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ fad_glb_host_request_body }}"
  register: fad_glb_host_post_result
  when: fad_glb_host_existing_data.json.payload.mkey is undefined
  changed_when: "fad_glb_host_post_result.json.payload == 0"
  failed_when: "fad_glb_host_post_result.json.payload != -15 and fad_glb_host_post_result.json.payload != 0"

- name: Update the GLB Host entry if the entry already exist and idempotent check failed for {{ fad_glb_host_name }}
  ansible.builtin.uri:
    method: PUT
    url: "{{ fad_api_endpoint_glb_hosts }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ fad_glb_host_request_body }}"
  register: fad_glb_host_put_result
  when: >
    (fad_glb_host_existing_data.json.payload['mkey'] is defined) and
    (
    fad_glb_host_existing_data.json.payload['default-feedback-ip'] != host.default_ipv4 | default('0.0.0.0') | string or
    fad_glb_host_existing_data.json.payload['default-feedback-ip6'] != host.default_ipv6 | default('::') | string or
    fad_glb_host_existing_data.json.payload['host-name'] != host.hostname or
    fad_glb_host_existing_data.json.payload['fortiview'] != host.fortiview | default('enable') or
    fad_glb_host_existing_data.json.payload['load-balance-method'] != host.load_balance_method | default('weight') or
    fad_glb_host_existing_data.json.payload['persistence'] != host.persistence | default('enable') or
    fad_glb_host_existing_data.json.payload['respond-single-record'] != host.respond_single_record | default('enable')
    )
  failed_when: "fad_glb_host_put_result.json.payload != -15 and fad_glb_host_put_result.json.payload != 0"

- name: Include the GLB Host VSP Lists task {{ fad_glb_host_name }}
  tags:
    - fad_glb_host_vsp_lists
  block:
    - name: Include the GLB Host VSP Lists task {{ fad_glb_host_name }}
      ansible.builtin.include_tasks: 01-a-glb-host-vsp-list.yaml
      loop: "{{ host.vsp_lists }}"
      loop_control:
        loop_var: vsp_list

- name: Check if the data have changed for {{ fad_glb_host_name }}
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_glb_hosts }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_glb_host_new_data
  changed_when: "fad_glb_host_new_data.json.payload != fad_glb_host_existing_data.json.payload"
  tags:
    - debug

- name: Print out the new value of GLB Host data for {{ fad_glb_host_name }}
  ansible.builtin.debug:
    var: fad_glb_host_new_data.json.payload
  tags:
    - debug

- name: Add GLB Host's Zone to DNS Policy if it hasn't for {{ fad_glb_host_name }}
  ansible.builtin.include_tasks: 01-b-dns-policy-zone-list.yaml
