- name: Set fact for GLB Host VSP List {{ vsp_list.pool_name }}
  ansible.builtin.set_fact:
    fad_api_endpoint_glb_host_vsp_lists: >-
      https://{{ ansible_host }}/api/global_load_balance_host_child_virtual_server_pool_list
      ?vdom={{ fad_vdom }}&pkey={{ fad_glb_host_name }}&mkey={{ vsp_list.mkey }}
    fad_glb_host_vsp_list_name: "{{ fad_glb_host_name }}/{{ vsp_list.pool_name }}"
    fad_glb_host_vsp_list_request_body: |
      {
        "mkey": "{{ vsp_list.mkey | string }}",
        "isp": "{{ vsp_list.isp | default('') }}",
        "topology": "{{ vsp_list.topology | default('') }}",
        "virtual-server-pool": "{{ vsp_list.pool_name }}",
        "weight": "{{ vsp_list.weight | default('100') | string }}"
      }
  delegate_to: localhost
  tags:
    - fad_glb_hosts_vsp_lists

- name: Print out the GLB Hosts REST API endpoint for {{ fad_glb_host_vsp_list_name }}
  ansible.builtin.debug:
    msg: "Current endpoint: {{ fad_api_endpoint_glb_host_vsp_lists }}"
  tags:
    - fad_glb_hosts_vsp_lists
    - debug

- name: Get the existing value of GLB Host VSP List data for {{ fad_glb_host_vsp_list_name }}
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_glb_host_vsp_lists }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_glb_host_vsp_list_existing_data
  delegate_to: localhost
  tags:
    - fad_glb_hosts_vsp_lists

- name: Print out the existing value of GLB Host VSP List data for {{ fad_glb_host_vsp_list_name }}
  ansible.builtin.debug:
    var: fad_glb_host_vsp_list_existing_data.json.payload
  delegate_to: localhost
  tags:
    - fad_glb_hosts_vsp_lists
    - debug

- name: Print out the Host VSP List request body json for {{ fad_glb_host_vsp_list_name }}
  ansible.builtin.debug:
    var: fad_glb_host_vsp_list_request_body
  tags:
    - fad_glb_host_vsp_list_name }}
    - debug

- name: Trying to create new GLB Host VSP list entry for {{ fad_glb_host_vsp_list_name }}
  ansible.builtin.uri:
    method: POST
    url: "{{ fad_api_endpoint_glb_host_vsp_lists }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ fad_glb_host_vsp_list_request_body }}"
  register: fad_glb_host_vsp_list_post_result
  when: fad_glb_host_vsp_list_existing_data.json.payload.mkey is undefined
  delegate_to: localhost
  changed_when: "fad_glb_host_vsp_list_post_result.json.payload == 0"
  failed_when: "fad_glb_host_vsp_list_post_result.json.payload != -15 and fad_glb_host_vsp_list_post_result.json.payload != 0"
  tags:
    - fad_glb_hosts_vsp_lists

- name: Update the GLB Host entry if the entry exist for {{ fad_glb_host_vsp_list_name }}
  ansible.builtin.uri:
    method: PUT
    url: "{{ fad_api_endpoint_glb_host_vsp_lists }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ fad_glb_host_vsp_list_request_body }}"
  register: fad_glb_host_vsp_list_put_result
  delegate_to: localhost
  when: >
    (fad_glb_host_vsp_list_existing_data.json.payload['mkey'] is defined) and
    (
    fad_glb_host_vsp_list_existing_data.json.payload['isp'] != vsp_list.isp | default('')  or
    fad_glb_host_vsp_list_existing_data.json.payload['topology'] != vsp_list.topology | default('') or
    fad_glb_host_vsp_list_existing_data.json.payload['virtual-server-pool'] != vsp_list.pool_name or
    fad_glb_host_vsp_list_existing_data.json.payload['weight'] != vsp_list.weight | default ('100') | string
    )
  failed_when: "fad_glb_host_vsp_list_put_result.json.payload != -15 and fad_glb_host_vsp_list_put_result.json.payload != 0"
  tags:
    - fad_glb_hosts_vsp_lists

- name: Check if the data have changed for {{ fad_glb_host_vsp_list_name }}
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_glb_host_vsp_lists }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_glb_host_vsp_list_new_data
  changed_when: "fad_glb_host_vsp_list_new_data.json.payload != fad_glb_host_vsp_list_existing_data.json.payload"
  delegate_to: localhost
  tags:
    - fad_glb_hosts_vsp_lists
    - debug

- name: Print out the new value of GLB Host VSP List data for {{ fad_glb_host_vsp_list_name }}
  ansible.builtin.debug:
    var: fad_glb_host_vsp_list_new_data.json.payload
  delegate_to: localhost
  tags:
    - fad_glb_hosts_vsp_lists
    - debug
