- name: Set fact for GLB Host FQDN ({{ item.scope }}_{{ item.hostname }}.{{ item.domain }}).
  ansible.builtin.set_fact:
    fad_glb_host_entry: "{{ item.scope }}_{{ item.hostname }}.{{ item.domain }}"
    fad_null: null
  delegate_to: localhost

- name: Get the existing value of GLB Host data ({{ fad_glb_host_entry }}).
  ansible.builtin.uri:
    method: GET
    url: "https://{{ ansible_host }}/api/global_load_balance_host?vdom={{ fad_vdom }}&mkey={{ fad_glb_host_entry }}"
    body_format: json
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
  register: fad_glb_host_existing_data
  delegate_to: localhost

- name: Print out the existing value of GLB Host data ({{ fad_glb_host_entry }}).
  ansible.builtin.debug:
    var: fad_glb_host_existing_data.json
  delegate_to: localhost
  tags:
    - debug

- name: Delete if data exists ({{ fad_glb_host_entry }}).
  ansible.builtin.uri:
    method: DELETE
    url: "https://{{ ansible_host }}/api/global_load_balance_host?vdom={{ fad_vdom }}&mkey={{ fad_glb_host_entry }}"
    body_format: json
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
  register: fad_glb_host_existing_data
  delegate_to: localhost
  when: fad_glb_host_existing_data.json.payload != fad_null
  changed_when: fad_glb_host_existing_data.json.payload == 0
  failed_when: fad_glb_host_existing_data.json.payload != 0

- name: Write request body json tmp file ({{ fad_glb_host_entry }}).
  ansible.builtin.copy:
    content: |
      {
        "default-feedback-ip": "{{ item.default_ipv4 }}",
        "default-feedback-ip6": "::",
        "host-name": "{{ item.hostname }}",
        "domain-name": "{{ item.domain }}.",
        "fortiview": "enable",
        "load-balance-method": "",
        "mkey": "{{ fad_glb_host_entry }}",
        "persistence": "enable",
        "respond-single-record": "enable",
        "vs_pool_list": [
          {% for pool in item.vs_pool %}
          {
            "isp": "",
            "mkey": "{{ pool.mkey }}",
            "topology": "",
            "virtual-server-pool": "{{ pool.pool_name }}",
            "weight": "{{ pool.weight }}"
          }{% if not loop.last %},{% endif %}
          {% endfor %}
        ],
        "vs_pool_list_count": ""
      }
    dest: "/tmp/fad_{{ fad_glb_host_entry }}_request_body.json"
  register: request_body
  delegate_to: localhost
  run_once: true

- name: Trying to create new GLB Host entry ({{ fad_glb_host_entry }}).
  ansible.builtin.uri:
    method: POST
    url: "https://{{ ansible_host }}/api/global_load_balance_host?vdom={{ fad_vdom }}&mkey={{ fad_glb_host_entry }}"
    body_format: json
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
    body: "{{ lookup('ansible.builtin.file', request_body.path) }}"
  register: fad_glb_host_new_data
  delegate_to: localhost
  changed_when: "fad_glb_host_new_data.json.payload == 0"
  failed_when: "fad_glb_host_new_data.json.payload != -15 and fad_glb_host_new_data.json.payload != 0"
  
# - name: Update the GLB Host entry ({{ fad_glb_host_entry }}).
  # ansible.builtin.uri:
    # method: PUT
    # url: "https://{{ ansible_host }}/api/global_load_balance_host?vdom={{ fad_vdom }}&mkey={{ fad_glb_host_entry }}"
    # body_format: json
    # validate_certs: false
    # return_content: yes
    # status_code: 200
    # headers:
      # 'Content-Type': 'application/json'
      # 'APITOKEN': '{{ fad_apitoken }}'
    # body: "{{ lookup('ansible.builtin.file', request_body.path) }}"
  # register: fad_glb_host_new_data
  # delegate_to: localhost
  # when: "fad_glb_host_new_data.json.payload == -15"
  # changed_when: "fad_glb_host_new_data.json.payload == 0"
  # failed_when: "fad_glb_host_new_data.json.payload != -15 and fad_glb_host_new_data.json.payload != 0"

- name: Get the new value of GLB Host data ({{ fad_glb_host_entry }}).
  ansible.builtin.uri:
    method: GET
    url: "https://{{ ansible_host }}/api/global_load_balance_host?vdom={{ fad_vdom }}&mkey={{ fad_glb_host_entry }}"
    body_format: json
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
  register: fad_glb_host_existing_data
  delegate_to: localhost
  tags:
    - debug

- name: Print out the new value of GLB Host data ({{ fad_glb_host_entry }}).
  ansible.builtin.debug:
    var: fad_glb_host_existing_data.json.payload
  delegate_to: localhost
  tags:
    - debug