- name: Write VSP request body json tmp file ({{ fad_glb_host_entry }} - {{ item.pool_name }}).
  ansible.builtin.copy:
    content: |
      {
        "isp": "",
        "mkey": "{{ item.mkey }}",
        "topology": "",
        "virtual-server-pool": "{{ item.pool_name }}",
        "weight": "{{ item.weight }}"
      }
    dest: "/tmp/fad_{{ fad_glb_host_entry }}_{{ item.pool_name }}_request_body.json"
    mode: u+rw,g-rw,o-rw
  register: glb_host_pool_request_body
  delegate_to: localhost
  run_once: true

- name: Trying to create new GLB Host VSP list entry ({{ fad_glb_host_entry }} - {{ item.pool_name }}).
  ansible.builtin.uri:
    method: POST
    url: "https://{{ ansible_host }}/api/global_load_balance_host_child_virtual_server_pool_list?vdom={{ fad_vdom }}&pkey={{ fad_glb_host_entry }}"
    body_format: json
    validate_certs: false
    return_content: true
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
    body: "{{ lookup('ansible.builtin.file', glb_host_pool_request_body.dest) }}"
  register: fad_glb_host_new_data
  delegate_to: localhost
  changed_when: "fad_glb_host_new_data.json.payload == 0"
  failed_when: "fad_glb_host_new_data.json.payload != -15 and fad_glb_host_new_data.json.payload != 0"

- name: Update the GLB Host entry for existing entry ({{ fad_glb_host_entry }} - {{ item.pool_name }}).
  ansible.builtin.uri:
    method: PUT
    url:  "https://{{ ansible_host }}/api/global_load_balance_host_child_virtual_server_pool_list?vdom={{ fad_vdom }}&pkey={{ fad_glb_host_entry }}&mkey={{ item.mkey }}"
    body_format: json
    validate_certs: false
    return_content: true
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
    body: "{{ lookup('ansible.builtin.file', glb_host_pool_request_body.dest) }}"
  register: fad_glb_host_new_data
  delegate_to: localhost
  when: "fad_glb_host_new_data.json.payload == -15"
  changed_when: "fad_glb_host_new_data.json.payload == 0"
  failed_when: "fad_glb_host_new_data.json.payload != -15 and fad_glb_host_new_data.json.payload != 0"