---

- name: Include the add GLB host task.
  tags:
    - fad_glb_hosts
  block:
    - name: Include the add GLB host task.
      ansible.builtin.include_tasks: 01-0-glb-host.yaml
      loop: "{{ fad_glb_hosts }}"
      loop_control:
        loop_var: host
