---

- name: Create/update GLB Hosts entries.
  vars:
    fad_glb_host_api_endpoint: "{{ fad_base_url + fad_api_endpoint.glb_host }}"
  ansible.builtin.import_tasks: fad_glb_host.yaml
  tags: [fad_glb_host]

- name: Create/update GLB Host VSP List entries.
  vars:
    fad_glb_host_vsp_list_api_endpoint: "{{ fad_base_url + fad_api_endpoint.glb_host_vsp_list }}"
  ansible.builtin.import_tasks: fad_glb_host_vsp_list.yaml
  tags: [fad_glb_host, fad_glb_host_vsp_list]

- name: Update DNS Policy zone list.
  vars:
    fad_dns_policy_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_policy }}"
  ansible.builtin.import_tasks: fad_dns_policy_zone_list_update.yaml
  tags: [fad_glb_host, fad_update_zone_list]
