---

- name: Create/update GLB Hosts entries.
  vars:
    fad_glb_host_api_endpoint: "{{ fad_base_url + fad_api_endpoint.glb_host }}"
  ansible.builtin.import_tasks: fad_glb_host.yaml
  tags: [fad_glb_host]

- name: Create/update GLB Host VSP List entries.
  vars:
    fad_glb_host_vsp_list_api_endpoint: "{{ fad_base_url + fad_api_endpoint.glb_host_vsp_list }}"
  ansible.builtin.import_tasks: fad_glb_host_vsp_list.yaml
  tags: [fad_glb_host, fad_glb_host_vsp_list]

- name: Update DNS Policy zone list.
  ansible.builtin.include_role:
    name: ndkprd.fad_dns_policy
  tags: [fad_glb_host]
